version = 0.1

[default]
[default.global.parameters]
stack_name = "villa-sdk-cache"

[default.build.parameters]
cached = true
parallel = true

[default.deploy.parameters]
capabilities = ["CAPABILITY_IAM", "CAPABILITY_NAMED_IAM"]
confirm_changeset = true
region = "us-east-1"
resolve_s3 = true
s3_prefix = "villa-sdk-cache"
template_file = "template.yaml"
parameter_overrides = [
    "BucketName=villa-ecommerce-sdk-cache",
    "EnableVersioning=true",
    "EnableLifecycleRules=true",
    "CacheRetentionDays=30"
]

